### PR TITLE
Add Ghostscript and Poppler-Utils to Image

### PR DESCRIPTION
**Pull request by abouillon**

### CODE REVIEW

**Comment by jackboberg** [comment]
Thanks for the PR @abouillon. I think I'd like to look at adding a property to `app.json` or `package.json` that allows you to list any system level dependencies, and we can `apt-get install` them at build time. This way, we don't keep adding more and more dependencies to the base image for everyone's edge case.

This change would be to our build service, which is not OS. I'll update this thread as we discuss or make progress internally.

**Comment by abouillon** [comment]
That sounds even better. At this point the only other way we could think of to get these dependencies for our project is to write an install script that would run when the project is installed on the base image.
Thank you for taking the time to review this.

**Comment by jackboberg** [comment]
Closing this PR for now, will deal with in other threads. Thanks again @abouillon

**Comment by abouillon** [comment]
Is there any sort of time estimate on getting system dependencies at build time?

**Comment by jackboberg** [comment]
We do not have a public roadmap at this time. I will update this issue as soon as I have something to share.

**Pull request closed without merging**
